### ISSUE TITLE
Invalid balances on wallet selector

### ISSUE THREAD

**Issue by wigy-opensource-developer** [novasamatech/nova-wallet-android#1347]
I have a few addresses, some balance is locked, some transferable. Still, the balances shown on the wallet selector widget neither matches the total balance nor the transferable one. Chosing some fiat or DOT does not help, does not match with any choice.

**Comment by valentunn** [comment]
Hey! Thanks for reporting. We are aware of this issue - it is caused to the fact that balances locked in crowdloans or nomination pool staking are not counted in total balance on the wallet selector. 
We have the task to fix it in our backlog

**Comment by alialobidm** [comment]
1. [](url)

**Comment by wigy-opensource-developer** [comment]
This bug seems to be fixed in v8.something already.
