### ISSUE TITLE
I Sent a Coin to My Nova Wallet. Coin Balance is Updated But Not the Transaction History

### ISSUE THREAD

**Issue by LadySinag** [novasamatech/nova-wallet-android#1535]
Hello, shalom! 

I sent a coin to my Nova Wallet. Coin balance is updated but not the transaction history. I have version 7.12.2...

The last transaction appearing in the history is the transfer I made on 12May24

Please advise what could be the issue and the next steps I should take to resolve it.

Thanks in advance.

**Comment by valentunn** [comment]
Hey! For support questions please email us to support@novawallet.io
